delete from subcategory where CategoryID>0;
delete from category where CategoryID>10;
INSERT INTO category(CategoryID,CategoryName) VALUES(1,'Arts & Photography');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES(1,'Architecture'),
  (1,'Bussiness of Art'),
  (1,'Collections, Catalogs & Exhibitions'),
  (1,'Decorative Arts & Design'),
  (1,'Drawing'),
  (1,'Fashion'),
  (1,'Graphic Design'),
  (1,'History & Criticism'),
  (1,'Individual Artists'),
  (1,'Musics'),
  (1,'Other Media'),
  (1,'Painting'),
  (1,'Performing Arts'),
  (1,'Photography & Video'),
  (1,'Religious'),
  (1,'Sculpture'),
  (1,'Study & Teaching'),
  (1,'Vehicle Pictorials');
INSERT INTO category(CategoryID,CategoryName) VALUES(2,'Audible AudioBooks');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES(2,'Fiction & Literature'),
  (2,'Nonfiction'),
  (2,'Arts & Entairment'),
  (2,'Biographies & Memoirs'),
  (2,'Business & Investing'),
  (2,'Children''s Books'),
  (2,'Fantasy'),
  (2,'Health, Mind & Body'),
  (2,'History'),
  (2,'Humor'),
  (2,'Language Instructuib'),
  (2,'Mysteries & Thrillers'),
  (2,'Politics & Current Events'),
  (2,'Religion & Spirituality'),
  (2,'Romance'),
  (2,'Science'),
  (2,'Science Fiction'),
  (2,'Teens');
INSERT INTO category(CategoryID,CategoryName) VALUES(3,'Biographies');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES(3,'Arts & Literature'),
  (3,'Ethnic & National'),
  (3,'Historical'),
  (3,'Leaders & Notable People Memories'),
  (3,'Professionals & Academics'),
  (3,'Reference & Collections'),
  (3,'Regional Canada'),
  (3,'Regional U.S.'),
  (3,'Speific Groups'),
  (3,'Sports & Outdoors'),
  (3,'Travelers & Explores'),
  (3,'True Crime');
INSERT INTO category(CategoryID,CategoryName) VALUES(4,'Books on CD');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES (4,'Biographies & Memories'),
  (4,'Business'),
  (4,'Children''s Fiction'),
  (4,'Computer and Internet'),
  (4,'Cooking Food and Wine'),
  (4,'General'),
  (4,'Health, Mind % Body'),
  (4,'Hisotry'),
  (4,'Horror'),
  (4,'Humor'),
  (4,'Languages'),
  (4,'Literature & Fictions'),
  (4,'Music'),
  (4,'Myster & Thrillers'),
  (4,'Nonfiction'),
  (4,'Parenting & Families'),
  (4,'Poetry & Drama'),
  (4,'Radio Shows'),
  (4,'Reference'),
  (4,'Religion & Spiraituality'),
  (4,'Romance'),
  (4,'Science Fiction & Fantasy');
INSERT INTO category(CategoryID,CategoryName) VALUES(5,'Bussiness & Money');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES(5,'Accounting'),
  (5,'Biography & History'),
  (5,'Business Culture'),
  (5,'Economics'),
  (5,'Education & Reference'),
  (5,'Finance'),
  (5,'Human Resources'),
  (5,'Industries'),
  (5,'Insurance'),
  (5,'International'),
  (5,'Investing'),
  (5,'Job Hunting & Carrers'),
  (5,'Management & Leadership'),
  (5,'Marketing & Sales'),
  (5,'Personal Finance'),
  (5,'Processes & Infrastructure'),
  (5,'Real Estate'),
  (5,'Skills'),
  (5,'Small BUsiness & Entrepreneurship'),
  (5,'Taxation');
INSERT INTO category(CategoryID,CategoryName) VALUES(6,'Children''s Books');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES(6,'Action & Adventure'),
  (6,'Activities, Crafts & Games'),
  (6,'Animals'),
  (6,'Arts, Music & Photography'),
  (6,'Biographies'),
  (6,'Cars, Trains & Things to do'),
  (6,'Children Cookbooks'),
  (6,'Classics'),
  (6,'Comics & Graphic Novels'),
  (6,'Computer & Technology'),
  (6,'Early Learning'),
  (6,'Education & Reference'),
  (6,'Fairy Tales, Folk Tales & Myths'),
  (6,'Geography & Culture'),
  (6,'Growing Up & Facts of Life'),
  (6,'History'),
  (6,'Literature & Fiction'),
  (6,'Mysteries & Detectives'),
  (6,'Religions'),
  (6,'Science Fiction & Fantasy'),
  (6,'Science, Nature & How it works'),
  (6,'Sports & Outdoors');
INSERT INTO category(CategoryID,CategoryName) VALUES(7,'Christian Books & Bibles');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES
  (7,'Bibles'),
  (7,'Bibles Covers'),
  (7,'Bible Study & Reference'),
  (7,'Biographics'),
  (7,'Catholicism'),
  (7,'Children''s & Teens'),
  (7,'Christian Living'),
  (7,'Churches & Church Leadership'),
  (7,'Education'),
  (7,'History'),
  (7,'Literature & Fiction'),
  (7,'Mistory & Evangelism'),
  (7,'Protestantism'),
  (7,'Romance'),
  (7,'Theology'),
  (7,'Worship & Devotion');
INSERT INTO category(CategoryID,CategoryName) VALUES(8,'Comics & Graphies');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES
  (8,'Action & Adventure Manga'),
  (8,'Art of Comics and Manga'),
  (8,'Biographies & History Graphic Novel'),
  (8,'Comic Books'),
  (8,'Comic Strips'),
  (8,'Fantasy Graphic Novels'),
  (8,'Graphic Novels'),
  (8,'History & Price Guides'),
  (8,'How To Create Comics & Manga'),
  (8,'Manga'),
  (8,'Media Tie-In Graphic Novels'),
  (8,'Publishers'),
  (8,'Romance Manga'),
  (8,'Science Fiction Graphic Novels'),
  (8,'Superheroes');
INSERT INTO category(CategoryID,CategoryName) VALUES(9,'Computer & Technology');
INSERT INTO subcategory(CategoryID,SubCategoryName)
VALUES
  (9,'Business Technology'),
  (9,'Certification'),
  (9,'Computer Science'),
  (9,'Database & Big Data'),
  (9,'Digital Audio, Video & Photography'),
  (9,'Games & Strategy Guides'),
  (9,'Graphics & Design'),
  (9,'Hardware & DIY'),
  (9,'History & Culture'),
  (9,'Intertional & Social Media'),
  (9,'Mobile Phones, Tablets & E-Readers'),
  (9,'Networking & Cloud Computing'),
  (9,'Operating Systems'),
  (9,'Programming'),
  (9,'Security & Encrption'),
  (9,'Software');
