SET foreign_key_checks=0;
TRUNCATE TABLE subcategory;
TRUNCATE TABLE category;
SET foreign_key_checks=1;
INSERT INTO category(CategoryID,CategoryName) VALUES(1,'Arts & Photography');
INSERT INTO subcategory(CategoryID,SubCategoryName)VALUES(1,'Architecture'),
(1,'Bussiness of Art'),
(1,'Collections, Catalogs & Exhibitions'),
(1,'Decorative Arts & Design'),
(1,'Drawing'),
(1,'Fashion'),
(1,'Graphic Design'),
(1,'History & Criticism'),
(1,'Individual Artists'),
(1,'Musics'),
(1,'Other Media'),
(1,'Painting'),
(1,'Performing Arts'),
(1,'Photography & Video'),
(1,'Religious'),
(1,'Sculpture'),
(1,'Study & Teaching'),
(1,'Vehicle Pictorials');
INSERT INTO category(CategoryID,CategoryName) VALUES(2,'Audible AudioBooks');
INSERT INTO subcategory(CategoryID,SubCategoryName)VALUES(2,'Fiction & Literature'),
(2,'Nonfiction'),
(2,'Arts & Entairment'),
(2,'Biographies & Memoirs'),
(2,'Business & Investing'),
(2,'Children''s Books'),
(2,'Fantasy'),
(2,'Health, Mind & Body'),
(2,'History'),
(2,'Humor'),
(2,'Language Instructuib'),
(2,'Mysteries & Thrillers'),
(2,'Politics & Current Events'),
(2,'Religion & Spirituality'),
(2,'Romance'),
(2,'Science'),
(2,'Science Fiction'),
(2,'Teens');
INSERT INTO category(CategoryID,CategoryName) VALUES(3,'Biographies');
INSERT INTO subcategory(CategoryID,SubCategoryName)VALUES(3,'Arts & Literature'),
(3,'Ethnic & National'),
(3,'Historical'),
(3,'Leaders & Notable People Memories'),
(3,'Professionals & Academics'),
(3,'Reference & Collections'),
(3,'Regional Canada'),
(3,'Regional U.S.'),
(3,'Speific Groups'),
(3,'Sports & Outdoors'),
(3,'Travelers & Explores'),
(3,'True Crime');
INSERT INTO category(CategoryID,CategoryName) VALUES(4,'Books on CD');
INSERT INTO subcategory(CategoryID,SubCategoryName)VALUES(4,'Biographies & Memories'),
(4,'Business'),
(4,'Children''s Fiction'),
(4,'Computer and Internet'),
(4,'Cooking Food and Wine'),
(4,'General'),
(4,'Health, Mind & Body'),
(4,'Hisotry'),
(4,'Horror'),
(4,'Humor'),
(4,'Languages'),
(4,'Literature & Fictions'),
(4,'Music'),
(4,'Myster & Thrillers'),
(4,'Nonfiction'),
(4,'Parenting & Families'),
(4,'Poetry & Drama'),
(4,'Radio Shows'),
(4,'Reference'),
(4,'Religion & Spiraituality'),
(4,'Romance'),
(4,'Science Fiction & Fantasy'),
(4,'TV Show');
INSERT INTO category(CategoryID,CategoryName) VALUES(5,'Bussiness & Money');
INSERT INTO subcategory(CategoryID,SubCategoryName)VALUES(5,'Accounting'),
(5,'Biography & History'),
(5,'Business Culture'),
(5,'Economics'),
(5,'Education & Reference'),
(5,'Finance'),
(5,'Human Resources'),
(5,'Industries'),
(5,'Insurance'),
(5,'International'),
(5,'Investing'),
(5,'Job Hunting & Carrers'),
(5,'Management & Leadership'),
(5,'Marketing & Sales'),
(5,'Personal Finance'),
(5,'Processes & Infrastructure'),
(5,'Real Estate'),
(5,'Skills'),
(5,'Small BUsiness & Entrepreneurship'),
(5,'Taxation');
INSERT INTO category(CategoryID,CategoryName) VALUES(6,'Computer & Technology');
INSERT INTO subcategory(CategoryID,SubCategoryName)VALUES(6,'Business Technology'),
(6,'Certification'),
(6,'Computer Science'),
(6,'Database & Big Data'),
(6,'Digital Audio, Video & Photography'),
(6,'Games & Strategy Guides'),
(6,'Graphics & Design'),
(6,'Hardware & DIY'),
(6,'History & Culture'),
(6,'Intertional & Social Media'),
(6,'Mobile Phones, Tablets & E-Readers'),
(6,'Networking & Cloud Computing'),
(6,'Operating Systems'),
(6,'Programming'),
(6,'Security & Encrption'),
(6,'Software'),
(6,'Web Development & Design');